### ISSUE TITLE
Setting preseed through `daemon.preseed` fails on Ubuntu Core

### ISSUE THREAD

**Issue by hamistao** [canonical/lxd#13818] opened 2024-07-25 08:29 UTC
# Required information

 * Distribution: Ubuntu Core 22
 * snap: latest/edge
 * LXD version: 6.1

# Issue description

This is related to [this](https://chat.canonical.com/canonical/pl/d1sqonf8htnuf86838nos6wnwh) discussion.
Setting a LXD config preseed through `snap set lxd daemon.preseed="${preseed}"` fails to take effect on Ubuntu Core.

# Steps to reproduce
 1. snap install lxd
 2. snap set lxd daemon.preseed="$(cat /path/to/preseed.yaml)" # Requires having a preseed ready
 4. systemctl start snap.lxd.daemon
 5. lxc profile default show # The configuration on preseed.yaml does not take effect, I used profiles but one could use other methods to check for this

**Comment by hamistao** [comment] 2024-07-25 08:33
I believe I managed to narrow it down to [this](https://github.com/hamistao/lxd-pkg-snap/blob/f766c117e9b6eb214b77d1a8dcfdf3d77d5e4cc3/snapcraft/commands/daemon.start#L758) check that seems to fail on Core when it shouldn't. Also reproduced the problem on Core24.

**Comment by tomponline** [comment] 2024-07-25 15:14
@simondeziel may have thoughts around this too.

**Comment by WizardBit** [comment] 2024-07-25 23:32
Here's my complete reproducer done with multipass.
```bash
multipass launch core22 -n mycore22
multipass shell mycore22

sudo snap install lxd

cat <<EOF > preseed.yaml
config:
  images.auto_update_interval: 15
networks:
  - name: lxdbr0
    type: bridge
    config:
      ipv4.address: auto
      ipv6.address: none
EOF

sudo snap set lxd daemon.preseed="$(cat /home/ubuntu/preseed.yaml)"

# The preseed.yaml does get passed to LXD, but does not initalize LXD.
# Its worth noting, LXD does not check if the preseed.yaml is valid and gives no warning. This can be set to any string.
cat /var/snap/lxd/common/init.yaml
```

**Comment by boltmark** [comment] 2024-07-25 23:37
> I believe I managed to narrow it down to [this](https://github.com/hamistao/lxd-pkg-snap/blob/f766c117e9b6eb214b77d1a8dcfdf3d77d5e4cc3/snapcraft/commands/daemon.start#L758) check that seems to fail on Core when it shouldn't. Also reproduced the problem on Core24.

Thanks @hamistao, you were correct.

This issue is not specific to Core. We're essentially starting lxd before we make the check to see if it is the first time we've started it... which means the check will always fail. Since we depend on this check to handle preseeds, we end up never actually handling them. Moving the check before we start lxd resolves this.

**Comment by hamistao** [comment] 2024-07-26 02:16
@WizardBit Can you confirm wether setting `daemon.preseed` took effect on non-core Ubuntu?

**Comment by tomponline** [comment] 2024-07-26 07:08
@boltmark can you identity which commit introduce that issue please, thanks

**Comment by tomponline** [comment] 2024-07-26 07:11
Ah looks like it was this one:  https://github.com/canonical/lxd-pkg-snap/commit/14cf45b4f08086be8b288a0f4f80999bd9bd10b0

**Comment by WizardBit** [comment] 2024-07-26 15:24
Sure here's my reproducer with LXD for Ubuntu 22.04 (non-core). The preseed is from the output yaml from `lxd init`.

preseed.yaml
```
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  name: lxdbr0
  type: ""
  project: default
storage_pools:
- config:
    size: 5GiB
  description: ""
  name: default
  driver: zfs
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
```

Commands to reproduce
```
lxc launch ubuntu:22.04 vm1 --vm --profile default

lxc shell vm1

# preseed from above
sudo snap set lxd daemon.preseed="$(cat /root/preseed.yaml)"

# Check for yaml
cat /var/snap/lxd/common/init.yaml

# Wait a minute or two
lxc network ls -f compact
   NAME     TYPE    MANAGED       IPV4                 IPV6             DESCRIPTION  USED BY   STATE   
  enp5s0  physical  NO                                                               0                 
  lxdbr0  bridge    YES      10.67.108.1/24  fd42:f817:5585:bb76::1/64               1        CREATED 
  
lxc storage show default
config:
  size: 5GiB
  source: /var/snap/lxd/common/lxd/disks/default.img
  zfs.pool_name: default
description: ""
name: default
driver: zfs
used_by:
- /1.0/profiles/default
status: Created
locations:
- none
```

**Comment by WizardBit** [comment] 2024-07-26 16:38
Just to add, I'm wondering if there's any change of behavior due to LXD being preinstalled in server ISOs vs Ubuntu Core 22.04 which needs to be installed.

**Comment by WizardBit** [comment] 2024-07-26 16:49
That seems to have done it. So, it does affect both Ubuntu Core and Non-Core versions as long as LXD is not preinstalled.

```
lxc launch ubuntu:22.04 vm1 --vm --profile default

lxc shell vm1

snap remove --purge lxd
snap install lxd

# preseed from above
sudo snap set lxd daemon.preseed="$(cat /root/preseed.yaml)"

# Check for yaml
cat /var/snap/lxd/common/init.yaml

# Wait a minute or two
lxc network ls -f compact
   NAME     TYPE    MANAGED  IPV4  IPV6  DESCRIPTION  USED BY  STATE  
  enp5s0  physical  NO 
  
lxc storage show default
Error: Storage pool not found
```

**Comment by tomponline** [comment] 2024-07-26 16:53
Itll be specific versions of lxd, most likely 5.21.2 and 6.1

**Comment by tomponline** [comment] 2024-07-26 16:56
Ill get this fix back ported info the 5.21 lts series

**Comment by WizardBit** [comment] 2024-07-26 17:26
This does seem to affect 5.0 as well, but not 4.0

**Comment by tomponline** [comment] 2024-07-26 18:13
Ok thanks for the info.

**Comment by tomponline** [comment] 2024-09-03 22:28
This is fixed in https://discourse.ubuntu.com/t/lxd-5-21-2-lts-interim-snap-release-5-21-2-22f93f4-and-5-21-2-2f4ba6b/47331

https://github.com/canonical/lxd-pkg-snap/pull/537

https://github.com/canonical/lxd-pkg-snap/pull/537

**Closed by tomponline** 2024-09-03 22:28 UTC
Labels: Bug
