### ISSUE TITLE
Instance deletion fails on rbd storage

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#11685] opened 2023-05-16 08:54 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * LXD version: 5.13
   * Storage backend in use: rbd

# Issue description

An error happens on instance deletion "Failed to run rbd rm" -- see also the screenshot below from the LXD UI. It sent many requests to delete instances in parallel before the screenshot was taken. I assume it is a problem from the storage layer ceph / rdb.

Ideally the error would be avoided, maybe the error message can be improved -- or we can have some retry logic.

Or we can force-close the connection/mount to the storage if this error happens on instance deletion?

![Screenshot from 2023-05-15 19-16-22](https://github.com/canonical/lxd/assets/1155472/954c0929-e6f6-4979-8a1b-3e4e145f72ea)

related to #11546

**Comment by tomponline** [comment] 2023-05-30 13:19
@grebennikov I understand you originally encountered this issue.

Are you able to reproduce it? Thanks

**Comment by gabrielmougard** [comment] 2023-09-08 16:38
@edlerd do you still have this screenshot ? The link seems to be broken.. Also, can you give a bit more context in the steps to follow so that I can try to reproduce this ? Thanks.

**Comment by edlerd** [comment] 2023-09-08 17:43
> @edlerd do you still have this screenshot ? The link seems to be broken.. Also, can you give a bit more context in the steps to follow so that I can try to reproduce this ? Thanks.

Hey @gabrielmougard yes I restored the original screen in the ticket above. This was sent to me by our colleague Andrey Grebennikov so I can't provide more detail, maybe he still remembers if you ask him?

**Comment by grebennikov** [comment] 2023-09-13 15:09
I suspect the reason for the issue may be related to the fact that I tried to delete in batch, and it took some time. While the actual deletion is being processed the UI doesn't reflect it (for ex saying "deleting"), but still showing the machines as "running". I probably tried to perform it once again hence the delete call has been issued again and it broke the backend in some way.

**Comment by tomponline** [comment] 2024-01-17 10:55
@edlerd did you manage to reproduce this yet?

**Comment by tomponline** [comment] 2024-03-18 17:00
Lets close this for now as we have no reproducer.

**Closed by tomponline** 2024-03-18 17:00 UTC
Labels: Bug, Incomplete
