### ISSUE TITLE
Add all-projects param to the operation API

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#11808] opened 2023-06-08 16:00 UTC
# Issue description

Please add a parameter for `all-projects` to the [operation get request](https://github.com/lxc/lxd/blob/master/lxd/operations.go#L450) of the API. It should work similar to the parameter in the [events](https://github.com/lxc/lxd/blob/master/lxd/events.go#L48) endpoint. When `all-projects` is set, the returned list should not be filtered.

Add the swagger documentation for the new parameter and also add the `project` parameter, which is currently [not mentioned in the docs](https://linuxcontainers.org/lxd/docs/master/api/#/operations/operations_get).

Also add both parameters [to the docs](https://linuxcontainers.org/lxd/docs/master/api/#/operations/operations_get_recursion1) for the `1.0/operations?recursion=1` endpoint.

**Comment by tomponline** [comment] 2023-06-08 16:19
Isnt this a duplicate of https://github.com/lxc/lxd/issues/11616 ?

**Comment by stgraber** [comment] 2023-06-08 17:52
Yep, just makes sense to track separately given this one is a bit closer to being a bug when /1.0/events lets you get the data but /1.0/operations has no matching parameter.

**Comment by AuruTus** [comment] 2023-07-23 04:56
hi, i'm interested in this issue. Has it been assigned?

**Comment by tomponline** [comment] 2023-07-24 08:31
not yet, will assign to you.

**Comment by AuruTus** [comment] 2023-07-25 02:35
Ok, I'm on this feat. BTW, where should I update the doc? Or only that the swagger yaml and make it is needed?

**Closed** 2023-08-23 12:58 UTC
Labels: Feature, Easy
