### ISSUE TITLE
Live migrating a VM from a clustered node to a non-clustered LXD remote fails

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/lxd#12826] opened 2024-02-06 16:55 UTC
# Required information

 * Distribution: Ubuntut
 * Distribution version: 22.04
 * LXD version: git-5e6202c  latest/edge

# Issue description

I have 3 nodes with LXD. Two of them are clustered (`ceph01` and `ceph03`) and have a shared storage (ceph):
```
root@ceph01:~# lxd sql global 'select * from nodes'
+----+--------+-------------+--------------------+--------+----------------+--------------------------------+-------+------+-------------------+
| id |  name  | description |      address       | schema | api_extensions |           heartbeat            | state | arch | failure_domain_id |
+----+--------+-------------+--------------------+--------+----------------+--------------------------------+-------+------+-------------------+
| 1  | ceph01 |             | 10.104.79.114:8443 | 69     | 376            | 2024-02-06T15:33:11.86391567Z  | 0     | 2    | <nil>             |
| 2  | ceph03 |             | 10.104.79.115:8443 | 69     | 376            | 2024-02-06T15:33:18.226920195Z | 0     | 2    | <nil>             |
+----+--------+-------------+--------------------+--------+----------------+--------------------------------+-------+------+-------------------+
```

and a non-clustered `ceph02` node that is a remote of `ceph01`:
```
root@ceph01:~# lxd.lxc remote list
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
|         NAME         |                        URL                        |   PROTOCOL    |  AUTH TYPE  | PUBLIC | STATIC | GLOBAL |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
| ceph02               | https://10.104.79.80:8443                         | lxd           | tls         | NO     | NO     | NO     |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
| local (current)      | unix://                                           | lxd           | file access | NO     | YES    | NO     |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
| ubuntu               | https://cloud-images.ubuntu.com/releases          | simplestreams | none        | YES    | YES    | NO     |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
``` 

Having an instance `v1`:
```
lxc launch ubuntu:jammy v1 --vm --storage local --config migration.stateful=true --device root,size.state=2GiB
```

When I try to move this VM to the remote, I have this error:

```
root@ceph01:~# lxd.lxc move v1 ceph02:v1
Error: Failed instance creation: Failed creating instance record: Add instance info to the database: Failed to create "instances" entry: NOT NULL constraint failed: instances.node_id
```

**Comment by tomponline** [comment] 2024-02-06 16:58
So they are sharing the same ceph cluster, are they using different ceph pools?

**Comment by tomponline** [comment] 2024-02-06 16:58
@roosterfish is this something you're already aware of and been working on lately?

**Comment by gabrielmougard** [comment] 2024-02-06 17:01
Yes, sorry for not mentioning that, but `ceph01`, `ceph02` and `ceph03` all share the same ceph pool. It's just that `ceph02` is not in the LXD cluster.

**Comment by roosterfish** [comment] 2024-02-07 09:29
I haven't experienced this, but I am wondering why the same Ceph storage pool can be used for both the cluster (ceph01/ceph03) and ceph02. LXD creates a zero size placeholder volume to indicate that this Ceph pool is already used by a LXD storage pool. 

@gabrielmougard how did you add the Ceph storage pool to both the cluster and the standalone LXD? Did you run `lxc storage create` two times? Maybe the concept of the placeholder is off.

**Comment by gabrielmougard** [comment] 2024-02-07 10:07
Here is my step by step setup:
* Create a ceph cluster on `ceph01`, `ceph02`, `ceph03`
  * `microceph cluster bootstrap` on `ceph01` and then `microceph cluster add ceph02` and `microceph cluster add ceph02`
  
* Then, once the ceph cluster is created, I created my lxd cluster (`lxd init` with a cluster init + creating the `lxd` ceph pool on `ceph01` and `lxd init` with a cluster join token for `ceph03`)
* `ceph02` is just initiated with local storage only.
* Then `ceph02` is added as a remote of `ceph01`.

**Comment by tomponline** [comment] 2024-02-21 13:13
Hey @mseralessandri would you be able to help to confirm @gabrielmougard findings here and check its a general issue or whether its specific to his setup? Thanks!

**Comment by mseralessandri** [comment] 2024-03-20 10:24
Hi  @gabrielmougard I replicated your configuration but I could not reproduce the issue, neither with local storage nor with ceph. I installed the `edge` version of LXD on  three nodes (`maria01`, `maria02`, `maria03`), two are clustered (`maria01`, and `maria03`) and `maria02` is added as a remote. Below the complete list of step I did

```
###### Microceph cluster config #######
## on maria01 ##
microceph cluster bootstrap
microceph cluster add maria02 
microceph cluster add maria03

## on maria02 ##
microceph cluster join <maria02 token>

## on maria03 ##
microceph cluster join <maria03 token>

## on all nodes ##
microceph disk add /dev/vdb --wipe

###### LXD cluster config #######
## on maria01 ##
lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What IP address or DNS name should be used to reach this server? [default=10.142.21.143]: 
Are you joining an existing cluster? (yes/no) [default=no]: 
What member name should be used to identify this server in the cluster? [default=maria01]: 
Do you want to configure a new local storage pool? (yes/no) [default=yes]: 
Name of the storage backend to use (dir, lvm, zfs, btrfs) [default=zfs]: 
Create a new ZFS pool? (yes/no) [default=yes]: 
Would you like to use an existing empty block device (e.g. a disk or partition)? (yes/no) [default=no]: 
Size in GiB of the new loop device (1GiB minimum) [default=5GiB]: 
Do you want to configure a new remote storage pool? (yes/no) [default=no]: yes
Name of the storage backend to use (cephfs, cephobject, powerflex, ceph) [default=ceph]: ceph
Create a new CEPH pool? (yes/no) [default=yes]: yes
Name of the existing CEPH cluster [default=ceph]: 
Name of the OSD storage pool [default=lxd]: 
Number of placement groups [default=32]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: 
Would you like to create a new Fan overlay network? (yes/no) [default=yes]: 
What subnet should be used as the Fan underlay? [default=auto]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]: 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 

lxc config trust add 
Please provide client name: maria02
Client maria02 certificate add token: <maria02 token>

lxc config trust add 
Please provide client name: maria03
Client maria03 certificate add token: <maria03 token>

## on maria02 and maria03 using tokens generated in the previous steps ## 
lxc remote add maria01 https://10.142.21.143:8443

## on maria01 ##
lxc cluster add maria03
 
## on maria03 ##
lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What IP address or DNS name should be used to reach this server? [default=10.142.21.161]: 
Are you joining an existing cluster? (yes/no) [default=no]: yes
Do you have a join token? (yes/no/[token]) [default=no]: yes
Please provide join token: sudo lxc remote add maria01 https://10.142.21.143:8443
Invalid input: Invalid join token: illegal base64 data at input byte 4

Please provide join token:
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose "size" property for storage pool "local": 20GiB            
Choose "source" property for storage pool "local": /dev/vdc
Choose "zfs.pool_name" property for storage pool "local": default


## on maria02 ##
lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: no
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (powerflex, zfs, btrfs, ceph, dir, lvm) [default=zfs]: 
Create a new ZFS pool? (yes/no) [default=yes]: 
Would you like to use an existing empty block device (e.g. a disk or partition)? (yes/no) [default=no]: 
Size in GiB of the new loop device (1GiB minimum) [default=5GiB]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like the LXD server to be available over the network? (yes/no) [default=no]: yes
Address to bind LXD to (not including port) [default=all]: 
Port to bind LXD to [default=8443]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]: 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 

lxc config trust add
Please provide client name: maria01
Client maria01 certificate add token: <maria01 token>

## on maria01 ##
lxc remote add maria02 https://10.142.21.76:8443
Generating a client certificate. This may take a minute...
Certificate fingerprint: 34ea594437734013f791147e6f7abeb6a6d80847490fc4f115082be3a9ba46a7
ok (y/n/[fingerprint])? y
Admin password (or token) for maria02: 
Client certificate now trusted by server: maria02

# Launching v1 with local storage as per example on maria01 and moving it on maria02 
lxc launch ubuntu:jammy v1 --vm --storage local --config migration.stateful=true --device root,size.state=2GiB
lxc move v1 maria02:v1

# Launching v2 with ceph on maria01 and moving it on maria02 
lxc launch ubuntu:jammy v2 --vm --storage remote --config migration.stateful=true --device root,size.state=2GiB
sudo lxc move v2 maria02:v2

## on maria02 #
lxc list
+------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+
| NAME |  STATE  |         IPV4          |                      IPV6                       |      TYPE       | SNAPSHOTS |
+------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+
| v1   | RUNNING | 240.143.0.87 (enp5s0) | fd42:888c:d7fa:9132:216:3eff:fe44:db65 (enp5s0) | VIRTUAL-MACHINE | 0         |
+------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+
| v2   | RUNNING | 240.143.0.47 (enp5s0) |                                                 | VIRTUAL-MACHINE | 0         |
+------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+

**Comment by tomponline** [comment] 2024-03-28 10:08
@mseralessandri @gabrielmougard so should we close this?

**Comment by gabrielmougard** [comment] 2024-03-28 11:04
yes we can close this.

**Closed** 2024-03-28 11:05 UTC
Labels: Incomplete
