### ISSUE TITLE
Support automatically picking an external address for load-balancers and forwards

### ISSUE THREAD

**Issue by stgraber** [canonical/lxd#11665] opened 2023-05-11 11:16 UTC
In an environment where projects share a set of external addresses on the uplink network, it would be quite useful to have LXD support just picking an available address rather than require the user to find one.

This is particularly important in cases where the user can't see the other projects and so can't tell what's already in use without trying addresses one by one.

**Comment by tomponline** [comment] 2023-07-31 15:41
This seems like a duplicate of https://github.com/canonical/lxd/issues/11744

**Closed by tomponline** 2023-07-31 15:41 UTC
Labels: Feature

**Comment by stgraber** [comment] 2023-07-31 16:44
Yes, except this one was opened quite a bit before it :)

**Comment by tomponline** [comment] 2023-07-31 17:14
Yeah I kept the other one as there was more discussion on it.
