### ISSUE TITLE
docs: Can't find where to set profile options

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/lxd#12900] opened 2024-02-15 15:32 UTC
Googling "lxd profile configuration options" takes me to https://documentation.ubuntu.com/lxd/en/latest/profiles/ .  https://documentation.ubuntu.com/lxd/en/latest/profiles/#set-specific-options-for-a-profile says `Specify the profile name and the key and value of the instance option`. It'd be nice if it (or anywhere on the page) provided a link to those keys and values. It's also frustrating that https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/profile/device/set/#lxc-profile-device-set-md doesn't provide a link to the valid values either. I can't find anything under `Reference` about profile keys and values, so where else would it live?

---
*Reported from: https://documentation.ubuntu.com/lxd/en/latest/profiles/*

**Comment by tomponline** [comment] 2024-02-15 15:39
Sounds like a partial dupe of https://github.com/canonical/lxd/issues/12528

**Comment by ru-fu** [comment] 2024-02-15 15:52
> I can't find anything under `Reference` about profile keys and values, so where else would it live?

There are no special keys and values for profiles, but you can use profiles to set instance options, devices, and device options.
Those are documented here: https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/ (and subpages)

I agree that we should have a link to the options from the how-to though. Will add it. :)

**Closed** 2024-02-15 16:21 UTC
Labels: Documentation
