### ISSUE TITLE
lxc export exports snapshots although --instance-only is given

### ISSUE THREAD

**Issue by aivanise** [canonical/lxd#12433] opened 2023-10-20 13:52 UTC
* Distribution: ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux alexsv 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
   * LXC/LXD version: 
Name  Version       Rev    Tracking         Publisher   Notes
lxd   5.18-da72b8b  25945  latest/stable/…  canonical✓  in-cohort
   * Storage backend in use:
zfs

# Issue description

lxc export --instance-only exports metadata with snapshots, thus creating backups that are not importable

# Steps to reproduce

$ lxc launch ubuntu:22.04 test 
Creating test
Starting test                               
$ lxc snapshot test
$ lxc export test test-export.tar --instance-only 
Backup exported successfully!            
$ lxc rm -f test
$ lxc import test-export.tar test
Error: Failed importing backup: Failed checking snapshots: Snapshot count in backup config and storage device are different: Backup snapshots mismatch

**Comment by tomponline** [comment] 2023-10-20 14:05
Duplicate of https://github.com/canonical/lxd/issues/12370

Fixed in LXD 5.19 (currently in latest/candidate channel).

**Closed by tomponline** 2023-10-20 14:05 UTC
