### ISSUE TITLE
error lxd recover

### ISSUE THREAD

**Issue by hahau6** [canonical/lxd#12196] opened 2023-08-31 04:27 UTC
a new reinstall lxd and an old zfs pool, when I run lxd recover. 

lab@lab07:~$ zfs list
NAME                                                                              USED  AVAIL     REFER  MOUNTPOINT
default                                                                           528G  3.00T       96K  legacy
default/buckets                                                                    96K  3.00T       96K  legacy
default/containers                                                                523G  3.00T       96K  legacy
default/containers/buckets                                                         96K  3.00T       96K  legacy
default/containers/containers                                                      96K  3.00T       96K  legacy
default/containers/custom                                                          96K  3.00T       96K  legacy
default/containers/deleted                                                        576K  3.00T       96K  legacy
default/containers/deleted/buckets                                                 96K  3.00T       96K  legacy
default/containers/deleted/containers                                              96K  3.00T       96K  legacy
default/containers/deleted/custom                                                  96K  3.00T       96K  legacy
default/containers/deleted/images                                                  96K  3.00T       96K  legacy
default/containers/deleted/virtual-machines                                        96K  3.00T       96K  legacy
default/containers/images                                                          96K  3.00T       96K  legacy
default/containers/llm                                                            523G  3.00T      527G  legacy
default/containers/llm/buckets                                                     96K  3.00T       96K  legacy
default/containers/llm/containers                                                  96K  3.00T       96K  legacy
default/containers/llm/custom                                                      96K  3.00T       96K  legacy
default/containers/llm/deleted                                                    576K  3.00T       96K  legacy
default/containers/llm/deleted/buckets                                             96K  3.00T       96K  legacy
default/containers/llm/deleted/containers                                          96K  3.00T       96K  legacy
default/containers/llm/deleted/custom                                              96K  3.00T       96K  legacy
default/containers/llm/deleted/images                                              96K  3.00T       96K  legacy
default/containers/llm/deleted/virtual-machines                                    96K  3.00T       96K  legacy
default/containers/llm/images                                                      96K  3.00T       96K  legacy
default/containers/llm/virtual-machines                                            96K  3.00T       96K  legacy
default/containers/virtual-machines                                                96K  3.00T       96K  legacy
default/custom                                                                     96K  3.00T       96K  legacy
default/deleted                                                                   576K  3.00T       96K  legacy
default/deleted/buckets                                                            96K  3.00T       96K  legacy
default/deleted/containers                                                         96K  3.00T       96K  legacy
default/deleted/custom                                                             96K  3.00T       96K  legacy
default/deleted/images                                                             96K  3.00T       96K  legacy
default/deleted/virtual-machines                                                   96K  3.00T       96K  legacy
default/images                                                                   5.79G  3.00T       96K  legacy
default/images/097d5cad40b743c65693397fcc9bf95f83c009001c9f591a4cc47785fef06ece  5.79G  3.00T     5.79G  legacy
default/virtual-machines                                                           96K  3.00T       96K  legacy
---------------------------------

lab@lab07:~$ sudo lxd recover
This LXD server currently has the following storage pools:
Would you like to recover another storage pool? (yes/no) [default=no]: yes
Name of the storage pool: default
Name of the storage backend (cephfs, dir, lvm, zfs, ceph, btrfs): zfs
Source of the storage pool (block device, volume group, dataset, path, ... as applicable): default
Additional storage pool configuration property (KEY=VALUE, empty when done): zfs.pool_name=default
Additional storage pool configuration property (KEY=VALUE, empty when done):
Would you like to recover another storage pool? (yes/no) [default=no]:
The recovery process will be scanning the following storage pools:
 - NEW: "default" (backend="zfs", source="default")
Would you like to continue with scanning for lost volumes? (yes/no) [default=yes]: yes
Scanning for unknown volumes...
Error: Failed validation request: Failed checking volumes on pool "default": Failed to mount "default/containers/llm@snapshot-buckets" on "/var/snap/lxd/common/lxd/storage-pools/default/containers-snapshots/llm/buckets" using "zfs": no such file or directory

**Comment by hahau6** [comment] 2023-08-31 04:29
ubntu 20.04 lxd 5.15

**Comment by tomponline** [comment] 2023-09-01 07:32
Hi,

This looks like a duplicate of the support request over at https://discourse.ubuntu.com/t/error-when-lxd-recover-snapshot-file-cannot-be-found/38298 so I'll close this and we'll respond to you over there.

Github issues are preferred for confirmed bugs or feature requests rather than support.

Thanks

**Closed by tomponline** 2023-09-01 07:32 UTC
