### ISSUE TITLE
long device names don't show up properly under /dev/disk/by-id

### ISSUE THREAD

**Issue by digitalsignalperson** [canonical/lxd#12152] opened 2023-08-14 07:38 UTC
# Required information

 * Distribution: arch linux
 * Distribution version: rolling; uname -a `6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux`
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.39-1lts
   * LXC version: 5.15
   * LXD version: 5.15
   * Storage backend in use: zfs
  
# Issue description

I'm creating block devices with `lxc storage volume create` and attaching them to a VM. 
- If the name is long like "disk-arch-gen-work" it ends up garbled or non-existant in /dev/disk/by-id
- If the name is short like "agwork" it appears as expected in /dev/disk/by-id

# Steps to reproduce

1. My default pool is ZFS
2. Create two volumes
```
lxc storage volume create default disk-arch-gen-work size=10GiB --type=block
lxc storage volume create default disk-arch-gen-usb size=4GiB --type=block
```
3. attach to a new VM
```
lxc init images:archlinux "$VMNAME" --vm -c security.secureboot=false -c limits.memory=16GiB -c limits.cpu=$(nproc)
lxc storage volume attach default disk-arch-gen-work "$VMNAME"
lxc storage volume attach default disk-arch-gen-usb "$VMNAME"
```
4. Start VM and check names under /dev/disk/by-id
```
lxc start "$VMNAME"
lxc exec "$VMNAME" -- /bin/ls -l /dev/disk/by-id
```
The output is:
```
total 0
lrwxrwxrwx 1 root root  9 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_disk--arch--gen- -> ../../sdb
lrwxrwxrwx 1 root root  9 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_root -> ../../sda
lrwxrwxrwx 1 root root 10 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part2 -> ../../sda2
```
We get one one mangled "...disk--arch--gen-" that is wrong and cutoff.  If I look at lsblk I can see both the attached devices, unlabeled, under sdb and sdc.

Trying to shorten the name like this doesn't work (which the docs suggested [here](https://documentation.ubuntu.com/lxd/en/latest/howto/storage_volumes/#:~:text=If%20you%20want%20to%20use%20a%20different%20device%20name%2C%20you%20can%20add%20it%20to%20the%20command%3A)):
```
lxc storage volume attach default disk-arch-gen-work "$VMNAME" agwork
Error: Failed add validation for device "disk-arch-gen-work": Custom block volumes cannot have a path defined
```

If I delete everything and start again, but make short names instead like this

```
lxc storage volume create default agwork size=10GiB --type=block
lxc storage volume create default agusb size=4GiB --type=block
```
then the `lxc exec "$VMNAME" -- /bin/ls -l /dev/disk/by-id` output is 
```
total 0
lrwxrwxrwx 1 root root  9 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_agusb -> ../../sdb
lrwxrwxrwx 1 root root  9 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_agwork -> ../../sdc
lrwxrwxrwx 1 root root  9 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_root -> ../../sda
lrwxrwxrwx 1 root root 10 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part2 -> ../../sda2
```
Now we have the nice "..._agusb" and "..._agwork" names under /dev/disk/by-id as expected.

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

Some dmesg output from the VM
```
[    1.183158] sd 6:0:0:1: [sda] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    1.183212] sd 6:0:1:1: [sdb] 8388608 512-byte logical blocks: (4.29 GB/4.00 GiB)
[    1.183221] sd 6:0:0:1: [sda] Write Protect is off
[    1.183224] 9pnet: Installing 9P2000 support
[    1.183225] sd 6:0:0:1: [sda] Mode Sense: 63 00 00 08
[    1.183272] sd 6:0:1:1: [sdb] Write Protect is off
[    1.183275] sd 6:0:1:1: [sdb] Mode Sense: 63 00 00 08
[    1.183290] sd 6:0:2:1: Power-on or device reset occurred
[    1.183302] sd 6:0:0:1: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.183366] sd 6:0:2:1: [sdc] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    1.183393] sd 6:0:2:1: [sdc] Write Protect is off
[    1.183395] sd 6:0:2:1: [sdc] Mode Sense: 63 00 00 08
[    1.183439] sd 6:0:2:1: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.183516] sd 6:0:1:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.184277] sd 6:0:2:1: [sdc] Attached SCSI disk
[    1.184342] sd 6:0:1:1: [sdb] Attached SCSI disk
[    1.185418]  sda: sda1 sda2
[    1.185523] sd 6:0:0:1: [sda] Attached SCSI disk
```

lxc info arch-gen-vm --show-log
```
Name: arch-gen-vm
Status: RUNNING
Type: virtual-machine
Architecture: x86_64
PID: 2945638
Created: 2023/08/14 00:27 PDT
Last Used: 2023/08/14 00:27 PDT

Resources:
  Processes: 16
  Disk usage:
    root: 4.25MiB
  CPU usage:
    CPU usage (in seconds): 9
  Memory usage:
    Memory (current): 331.49MiB
  Network usage:
    enp5s0:
      Type: broadcast
      State: UP
      Host interface: tap83db779f
      MAC address: 00:16:3e:65:e8:f9
      MTU: 1500
      Bytes received: 12.88kB
      Bytes sent: 4.59kB
      Packets received: 63
      Packets sent: 48
      IP addresses:
        inet:  10.62.222.60/24 (global)
        inet6: fd42:2b0c:af1c:963e:216:3eff:fe65:e8f9/64 (global)
        inet6: fe80::216:3eff:fe65:e8f9/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 6.32kB
      Bytes sent: 6.32kB
      Packets received: 80
      Packets sent: 80
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Log:

```

lxc config show "$VMNAME" --expanded
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Archlinux current amd64 (20230813_04:18)
  image.os: Archlinux
  image.release: current
  image.requirements.secureboot: "false"
  image.serial: "20230813_04:18"
  image.type: disk-kvm.img
  image.variant: default
  limits.cpu: "16"
  limits.memory: 16GiB
  security.secureboot: "false"
  volatile.base_image: 785404235b064acd527bac25d21fe76fdc79ea943e3fc2e8c66f691ba362c6d5
  volatile.cloud-init.instance-id: 11a33e06-dc6c-44ce-b3e0-d3009d055483
  volatile.eth0.host_name: tap83db779f
  volatile.eth0.hwaddr: 00:16:3e:65:e8:f9
  volatile.last_state.power: RUNNING
  volatile.uuid: 40532d25-18ed-4f8f-ae5b-a9c8661dfb80
  volatile.uuid.generation: 40532d25-18ed-4f8f-ae5b-a9c8661dfb80
  volatile.vsock_id: "20"
devices:
  disk-arch-gen-usb:
    pool: default
    source: disk-arch-gen-usb
    type: disk
  disk-arch-gen-work:
    pool: default
    source: disk-arch-gen-work
    type: disk
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

/var/log/lxd/lxd.log - nothing while reproducing this

Also after doing a lot of this creating and destroying to get info for this issue
```
lxc storage volume create default disk-arch-gen-work size=10GiB --type=block
lxc storage volume create default disk-arch-gen-usb size=4GiB --type=block
lxc storage volume delete default disk-arch-gen-work
lxc storage volume delete default disk-arch-gen-usb
lxc storage volume create default agwork size=10GiB --type=block
lxc storage volume create default agusb size=4GiB --type=block
lxc storage volume delete default agwork
lxc storage volume delete default agusb
```
I can no longer create the volumes
```
lxc storage volume create default agwork size=10GiB --type=block
Error: Failed locating zvol for deactivation: Could not locate a zvol for rpoolx/LOCAL/lxd/custom/default_agwork
```

**Comment by gabrielmougard** [comment] 2023-08-30 13:51
@tomponline thanks I'll check this out

**Comment by tomponline** [comment] 2023-09-13 14:57
Hrm, maybe.

Using QMP I can see this:

```
lxc config set v1 raw.qemu=" -qmp tcp:127.0.0.1:4444,server,nowait"
lxc start v1
telnet 127.0.0.1 4444
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
{"QMP": {"version": {"qemu": {"micro": 0, "minor": 2, "major": 6}, "package": "Debian 1:6.2+dfsg-2ubuntu6.13"}, "capabilities": ["oob"]}}
{"execute": "qmp_capabilities"}
{"return": {}}
{"timestamp": {"seconds": 1694616782, "microseconds": 318832}, "event": "VSERPORT_CHANGE", "data": {"open": true, "id": "qemu_serial"}}
{"execute": "query-block"}
{"return": [{"device": "pflash0", "locked": false, "removable": false, "inserted": {"iops_rd": 0, "detect_zeroes": "off", "image": {"virtual-size": 1966080, "filename": "/usr/share/OVMF/OVMF_CODE.fd", "format": "raw", "actual-size": 1966080, "dirty-flag": false}, "iops_wr": 0, "ro": true, "node-name": "#block135", "backing_file_depth": 0, "drv": "raw", "iops": 0, "bps_wr": 0, "write_threshold": 0, "encrypted": false, "bps": 0, "bps_rd": 0, "cache": {"no-flush": false, "direct": false, "writeback": true}, "file": "/usr/share/OVMF/OVMF_CODE.fd"}, "qdev": "/machine/system.flash0", "type": "unknown"}, {"device": "pflash1", "locked": false, "removable": false, "inserted": {"iops_rd": 0, "detect_zeroes": "off", "image": {"virtual-size": 131072, "filename": "/dev/fd/4", "format": "raw", "actual-size": 131072, "dirty-flag": false}, "iops_wr": 0, "ro": false, "node-name": "#block393", "backing_file_depth": 0, "drv": "raw", "iops": 0, "bps_wr": 0, "write_threshold": 0, "encrypted": false, "bps": 0, "bps_rd": 0, "cache": {"no-flush": false, "direct": false, "writeback": true}, "file": "/dev/fd/4"}, "qdev": "/machine/system.flash1", "type": "unknown"}, {"io-status": "ok", "device": "", "locked": false, "removable": false, "inserted": {"iops_rd": 0, "detect_zeroes": "off", "image": {"virtual-size": 10737418240, "filename": "/dev/fdset/0", "format": "file", "actual-size": 1768050688, "dirty-flag": false}, "iops_wr": 0, "ro": false, "node-name": "lxd_root", "backing_file_depth": 0, "drv": "file", "iops": 0, "bps_wr": 0, "write_threshold": 0, "encrypted": false, "bps": 0, "bps_rd": 0, "cache": {"no-flush": false, "direct": true, "writeback": true}, "file": "/dev/fdset/0"}, "qdev": "dev-lxd_root", "type": "unknown"}, {"io-status": "ok", "device": "", "locked": false, "removable": false, "inserted": {"iops_rd": 0, "detect_zeroes": "off", "image": {"virtual-size": 10737418240, "filename": "/dev/fdset/1", "format": "file", "actual-size": 0, "dirty-flag": false}, "iops_wr": 0, "ro": false, "node-name": "lxd_disk--arch--gen--work", "backing_file_depth": 0, "drv": "file", "iops": 0, "bps_wr": 0, "write_threshold": 0, "encrypted": false, "bps": 0, "bps_rd": 0, "cache": {"no-flush": false, "direct": true, "writeback": true}, "file": "/dev/fdset/1"}, "qdev": "dev-lxd_disk--arch--gen--work", "type": "unknown"}]}
```

So we see the ` "qdev": "dev-lxd_disk--arch--gen--work"` entry shows its being escaped (which is done by `escapedDeviceName := filesystem.PathNameEncode(driveConf.DevName)` in LXD), but ultimately passed through completely to QEMU.

**Comment by tomponline** [comment] 2023-09-13 15:03
On my VM I also see that udev has created 2 devices, both escaped, but 1 has a cut-off name and the other has the full name:

```
udevadm info /dev/sdb
P: /devices/pci0000:00/0000:00:01.1/0000:02:00.0/virtio6/host0/target0:0:1/0:0:1:1/block/sdb
N: sdb
L: 0
S: disk/by-id/scsi-SQEMU_QEMU_HARDDISK_lxd_disk--arch--gen--work
S: disk/by-id/scsi-0QEMU_QEMU_HARDDISK_lxd_disk--arch--gen-
S: disk/by-path/pci-0000:02:00.0-scsi-0:0:1:1
E: DEVPATH=/devices/pci0000:00/0000:00:01.1/0000:02:00.0/virtio6/host0/target0:0:1/0:0:1:1/block/sdb
E: DEVNAME=/dev/sdb
E: DEVTYPE=disk
E: DISKSEQ=2
E: MAJOR=8
E: MINOR=16
E: SUBSYSTEM=block
E: USEC_INITIALIZED=2232280
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=QEMU
E: SCSI_VENDOR_ENC=QEMU\x20\x20\x20\x20
E: SCSI_MODEL=QEMU_HARDDISK
E: SCSI_MODEL_ENC=QEMU\x20HARDDISK\x20\x20\x20
E: SCSI_REVISION=2.5+
E: ID_SCSI=1
E: ID_SCSI_INQUIRY=1
E: SCSI_IDENT_SERIAL=lxd_disk--arch--gen--work
E: SCSI_IDENT_LUN_VENDOR=lxd_disk--arch--gen-
E: ID_VENDOR=QEMU
E: ID_VENDOR_ENC=QEMU\x20\x20\x20\x20
E: ID_MODEL=QEMU_HARDDISK
E: ID_MODEL_ENC=QEMU\x20HARDDISK\x20\x20\x20
E: ID_REVISION=2.5+
E: ID_TYPE=disk
E: ID_BUS=scsi
E: ID_SERIAL=0QEMU_QEMU_HARDDISK_lxd_disk--arch--gen-
E: ID_SERIAL_SHORT=lxd_disk--arch--gen-
E: ID_SCSI_SERIAL=lxd_disk--arch--gen--work
E: MPATH_SBIN_PATH=/sbin
E: DM_MULTIPATH_DEVICE_PATH=0
E: ID_PATH=pci-0000:02:00.0-scsi-0:0:1:1
E: ID_PATH_TAG=pci-0000_02_00_0-scsi-0_0_1_1
E: DEVLINKS=/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_lxd_disk--arch--gen--work /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_lxd_disk--arch--gen- /dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:1:1
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

**Comment by tomponline** [comment] 2023-09-13 15:05
@digitalsignalperson what do you see for `udevadm info /dev/sdb` in your VM guest?

**Comment by gabrielmougard** [comment] 2023-09-14 07:26
@digitalsignalperson it looks like the `ID_SERIAL` is contacatenating `0QEMU_QEMU_HARDDISK_` with `ID_SERIAL_SHORT` and not `ID_SCSI_SERIAL` (this one is right)

**Comment by tomponline** [comment] 2023-09-14 07:50
LXD doesnt add udev rules to the guests - its operating system agnostic.

It seems like Ubuntu is somehow handling this better though as I can see the full path in Jammy OK.

**Comment by tomponline** [comment] 2023-09-14 07:56
@digitalsignalperson could try that though.

I suspect the way forward here is to use a shorter name or stop using `-` in the name and try using a different separator like `_`.

The same issue still occurs but it makes it slightly nicer to consume:

```
root@v1:~# ls /dev/disk/by-id/ -la | grep disk
lrwxrwxrwx 1 root root   9 Sep 14 07:54 scsi-0QEMU_QEMU_HARDDISK_lxd_disk_arch_gen_wo -> ../../sdb
lrwxrwxrwx 1 root root   9 Sep 14 07:54 scsi-SQEMU_QEMU_HARDDISK_lxd_disk_arch_gen_work -> ../../sdb
```

I don't think we should change the escaping because that will break any users who are using references in /dev/disk/by-id that contain `-`.

**Comment by gabrielmougard** [comment] 2023-09-14 08:05
@tomponline just out of curiosity, what was the thinking behind escaping `-` wiith `--` originaly ? Couldn't we just forbid this charactter in first place ?

**Comment by gabrielmougard** [comment] 2023-09-14 09:36
If this is not a bug, @tomponline shall we close this then ?

**Closed** 2023-09-14 09:59 UTC
Labels: Incomplete
